package org.example.shubackend.entity;

import java.util.EnumSet;
import java.util.Set;

public enum PermissionName {
    // 数据类型
    DATA_TYPES_CREATE, DATA_TYPES_READ, DATA_TYPES_UPDATE, DATA_TYPES_DELETE,
    // 设备角色
    DEVICE_ROLES_CREATE, DEVICE_ROLES_READ, DEVICE_ROLES_UPDATE, DEVICE_ROLES_DELETE,
    // 设备类型
    FACILITY_TYPES_CREATE, FACILITY_TYPES_READ, FACILITY_TYPES_UPDATE, FACILITY_TYPES_DELETE,
    // 位置
    LOCATIONS_CREATE, LOCATIONS_READ, LOCATIONS_UPDATE, LOCATIONS_DELETE,
    // 设备
    DEVICES_CREATE, DEVICES_READ, DEVICES_UPDATE, DEVICES_DELETE,
    DEVICE_PARAMETERS_CREATE, DEVICE_PARAMETERS_READ, DEVICE_PARAMETERS_UPDATE, DEVICE_PARAMETERS_DELETE,
    INSPECTION_PLANS_CREATE, INSPECTION_PLANS_READ, INSPECTION_PLANS_UPDATE, INSPECTION_PLANS_DELETE,
    INSPECTION_RECORDS_CREATE, INSPECTION_RECORDS_READ, INSPECTION_RECORDS_UPDATE, INSPECTION_RECORDS_DELETE,
    MAINTENANCE_ORDERS_CREATE, MAINTENANCE_ORDERS_READ, MAINTENANCE_ORDERS_UPDATE, MAINTENANCE_ORDERS_DELETE,
    MAINTENANCE_RECORDS_CREATE, MAINTENANCE_RECORDS_READ, MAINTENANCE_RECORDS_UPDATE, MAINTENANCE_RECORDS_DELETE,
    SPARE_PARTS_CREATE, SPARE_PARTS_READ, SPARE_PARTS_UPDATE, SPARE_PARTS_DELETE,
    EMERGENCY_PLANS_CREATE, EMERGENCY_PLANS_READ, EMERGENCY_PLANS_UPDATE, EMERGENCY_PLANS_DELETE,
    EMERGENCY_PLAN_TYPES_CREATE, EMERGENCY_PLAN_TYPES_READ, EMERGENCY_PLAN_TYPES_UPDATE, EMERGENCY_PLAN_TYPES_DELETE,
    TOKEN_CREATE, TOKEN_READ, TOKEN_UPDATE, TOKEN_DELETE,
    PERMISSIONS_CREATE, PERMISSIONS_READ, PERMISSIONS_UPDATE, PERMISSIONS_DELETE,
    ROLES_CREATE, ROLES_READ, ROLES_UPDATE, ROLES_DELETE;

    public static Set<PermissionName> crudFor(String table) {
        return EnumSet.of(
                valueOf(table + "_CREATE"),
                valueOf(table + "_READ"),
                valueOf(table + "_UPDATE"),
                valueOf(table + "_DELETE")
        );
    }
}